services:
  - type: web
    name: ikigai-backend
    env: docker          # <--- CAMBIO CLAVE: Ahora es docker
    dockerContext: ./backend # <--- Le decimos dÃ³nde mirar
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000