services:
  - type: web
    name: ikigai-backend
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: ikigai-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: ikigai-backend
          property: url
    autoDeploy: true